export const FETCH_LOGIN_BEGIN = 'FETCH_LOGIN_BEGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const ADD_SIGNUP_BEGIN = 'ADD_SIGNUP_BEGIN';
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS';
export const ADD_SIGNUP_FAILURE = 'ADD_SIGNUP_FAILURE';

export const FETCH_SEARCH_BEGIN = 'FETCH_SEARCH_BEGIN';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

export const GET_USER_BEGIN = 'GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const CHANGE_COLOR = 'CHANGE_COLOR';
