export const FETCH_LOGIN_BEGIN = 'FETCH_LOGIN_BEGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const ADD_SIGNUP_BEGIN = 'ADD_SIGNUP_BEGIN';
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS';
export const ADD_SIGNUP_FAILURE = 'ADD_SIGNUP_FAILURE';

export const FETCH_SEARCH_BEGIN = 'FETCH_SEARCH_BEGIN';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';

export const GET_USER_BEGIN = 'GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const CHANGE_COLOR = 'CHANGE_COLOR';

export const SUBMIT_FORM_BEGIN= 'SUBMIT_FORM_BEGIN';
export const SUBMIT_FORM_SUCCESS= 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE= 'SUBMIT_FORM_FAILURE';

export const SIGNINFORM_UPDATE = 'signinForm_Update';
export const GET_ALL_USER = 'GET_ALL_USER';

export const GET_BY_USER_ID ='GET_BY_USER_ID';

export const UPDATE_FORM_BEGIN= 'UPDATE_FORM_BEGIN';
export const UPDATE_FORM_SUCCESS= 'UPDATE_FORM_SUCCESS';
export const UPDATE_FORM_FAILURE= 'UPDATE_FORM_FAILURE';